
import "./globals.css";
import LayOut from "../components/LayOut";
import Header from "../components/Header";

export const metadata = {
  title: "Ecommarce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <LayOut>
          <div className="bg-white sticky top-0 z-50   shadow-md  bg-opacity-100">
            <Header />
          </div>
          {children}
        </LayOut>
      </body>
    </html>
  );
}
